services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "1212:1212"
    depends_on:
      - todoapp-db
  todoapp-db:
    image: "postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp_db
    restart: on-failure
    ports:
      - "5432:5432"
volumes:
  todoapp-db: