services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "1212:1212"
    depends_on:
      - hich-db
      - redis

  hich-db:
    image: "postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hich_db
    restart: on-failure
    ports:
      - "5432:5432"
  redis:
    image: "redis:6.2.2"
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

volumes:
  hich-db: