mode: development
service_name: hichapp
language: en
db:
  postgres:
    host: localhost
    name: ums
    port: 5432
    username: postgres
    password: postgres
    driver: postgres
    ssl: disable
    appName: ums
    migrations_url: file:./cmd/migration/scripts
    transaction_timeout: 120000
    max_idle_connection: 10
    max_open_connection: 10
    conn_max_lifetime: 120000
    trace_stacks: true
  redis:
    address: localhost:6380
    password:
    db: 0
  run_seeder: true
kafka:
  brokers:
    - localhost:30010
  group_id: hichapp-consumer-group
  debug_log: true
  from_beginning: true
  inbox_retry:
    max_retries: 3
    base_delay: 1000
    max_delay: 300000
    scale_factor: 2
  retry:
    retries: 1
    initial_interval: 100
  router:
    close_timeout: 1s
    retries: 5
    retries_interval_ms: 5
    sig_term_and_sig_int_handled_already: false
core:
  http:
    address: ":1212"
    port: 1212
  auth:
    jwt_secret_key: test
    ttl: 2000000m